version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app/
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 60
      runas: root
```

### C. Necessary CloudFormation Adjustment

To fully shift to a CI/CD model, the **`poc-infra.yaml`** file's `UserData` script must be edited to **remove** the `cat << 'EOF' ...` blocks that create the application files (`app.py`, `index.html`) and the database initialization command (`python3 /var/www/app/app.py`). These actions will be handled by the deployment package instead.

We can now move on to creating the **CI/CD pipeline**!
